# Generated by Django 5.0.2 on 2024-03-20 22:49

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to=pathlib.PureWindowsPath('C:/DjangoProject/myappm/music'))),
            ],
        ),
        migrations.AddConstraint(
            model_name='musicfile',
            constraint=models.CheckConstraint(check=models.Q(('title__isnull', False), ('title__gt', '')), name='title_not_empty'),
        ),
    ]
